import type { Metadata } from 'next';
import './globals.css';
import ProviderComponent from '@/components/Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-home_page font-bitter">
        <ProviderComponent>{children}</ProviderComponent>
      </body>
    </html>
  );
}
